apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 5
  template:
    metadata:
      labels:
        app: mywebapp
    spec:
      containers:
        - name: myapp
          image: zkan/fapi:dde48fcb
          ports:
            - containerPort: 8000
